// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('login-test', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('login-test', async function() {
    await driver.get("https://myemm.work/auth/login")
    await driver.manage().window().setRect({ width: 968, height: 948 })
    await driver.findElement(By.id("input-44")).click()
    await driver.findElement(By.id("input-44")).sendKeys("t5kuboki@gmail.com")
    await driver.findElement(By.id("input-47")).click()
    await driver.findElement(By.id("input-47")).sendKeys("test123!!")
    await driver.findElement(By.css(".v-input--selection-controls__ripple")).click()
    {
      const element = await driver.findElement(By.css(".primary > .v-btn__content"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".primary > .v-btn__content")).click()
    await driver.findElement(By.css(".v-expansion-panel:nth-child(1) p")).click()
    await driver.findElement(By.css(".v-expansion-panel-header--active > p")).click()
  })
})
