name: Run Selenium Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.12.2"
      - run: npm ci
      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
      - name: Install Chrome WebDriver
        run: |
          wget https://chromedriver.storage.googleapis.com/90.0.4430.24/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin
      - name: Run tests and save results
        run: npm test > test-results.json
      - name: Analyze test results
        run: python analyze_results.py > analysis-results.txt
      - name: Send results via email
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.resend.com
          server_port: 465
          username: ${{ secrets.RESEND_USERNAME }}
          password: ${{ secrets.MAIL_API_KEY }}
          subject: Test result in ${{ github.repository }}
          to: ${{ secrets.MAIL_TO }}
          from: GitHub Actions <${{ secrets.MAIL_FROM }}>
          body: Check the logs at ${{ github.server_url }}/${{ github.repository }}/actions
          attachments: analysis-results.txt
