name: Run Selenium Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.12.2"
      - run: npm ci
      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
      - name: Install Chrome WebDriver
        run: |
          wget https://chromedriver.storage.googleapis.com/90.0.4430.24/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin
      - name: Run tests and save results
        run: npm test > test-results.json
      - name: Commit results
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add test-results.txt
          git commit -m "Add test results" || echo "No changes to commit"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
      - name: Send results via email
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.resend.com
          server_port: 465
          username: ${{ secrets.RESEND_USERNAME }}
          password: ${{ secrets.MAIL_API_KEY }}
          subject: Test result in ${{ github.repository }}
          to: ${{ secrets.MAIL_TO }}
          from: GitHub Actions <${{ secrets.MAIL_FROM }}>
          body: Check the logs at ${{ github.server_url }}/${{ github.repository }}/actions
          attachments: test-results.json
